### ISSUE TITLE
Link from graphql-code-generator repo?

### ISSUE THREAD

**Issue by dotansimha** [adamkl/graphql-xsd#3]
Hi @adamkl !

I recently saw your project, and I noticed that you are using my code-generator :) 
Just to let you know - a new version of the codegen is out and now it's much easier to create a custom template. You also can also now implement your template as NPM package and the codegen knows how to use it directly (templates are no longer coupled to the code-gen core).

Also - is that okay to link to this repo from the codegen's repo?

**Comment by adamkl** [comment]
Yes, you can definitely link to this repo if you'd like!

And I apologize for my less than stellar use of your great tool. I've been doing a lot of work with GraphQL APIs (merging, stitching, and proxying them) and have found a lot of uses for your library as we work on the different components of our solution. 

I needed a way to easily generate different types of code based off of GraphQL schemas and the best I could come up with at the time was to wrap your library and pretend that it was being executed via CLI. 

Not my preferred approach so I will definitely take a look at the latest version of `graphql-code-generator` to see if I can refactor things into simple template packages. That would be a better approach for everyone.
